version: '3.8'

services:
  crowdsec-web-ui:
    image: ghcr.nju.edu.cn/theduffman85/crowdsec-web-ui:latest
    container_name: crowdsec_web_ui
    ports:
      - "3000:3000"
    environment:
      - CROWDSEC_URL=http://127.0.0.1:18081
      - CROWDSEC_USER=crowdsec-web-ui
      - CROWDSEC_PASSWORD=${CROWDSEC_WEB_UI_PASSWORD}
      - CROWDSEC_LOOKBACK_PERIOD=5d
      - CROWDSEC_REFRESH_INTERVAL=30s
      - CROWDSEC_IDLE_REFRESH_INTERVAL=5m
      - CROWDSEC_IDLE_THRESHOLD=2m
      - CROWDSEC_FULL_REFRESH_INTERVAL=5m
    volumes:
      - crowdsec_web_ui_data:/app/data
    restart: unless-stopped
    network_mode: host

volumes:
  crowdsec_web_ui_data:
    driver: local